### ISSUE TITLE
ArrayIndexOutOfBoundsException when serializing generic classes

### ISSUE THREAD

**Issue by theigl** [EsotericSoftware/kryo#654]
Using Kryo 5.0.0-RC3-SNAPSHOT, I get the following Stacktrace when running the test:

```
com.esotericsoftware.kryo.KryoException: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
Serialization trace:
input (SerializeTest$StringSupplierContainer)
	at com.esotericsoftware.kryo.serializers.ReflectField.write(ReflectField.java:92)
	at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:107)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:630)
```

```
import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.io.Output;
import org.junit.jupiter.api.Test;

import java.io.Serializable;
import java.util.function.Supplier;

import static org.assertj.core.api.Assertions.assertThat;

public class SerializeTest {

	@Test
	void serialize() {
		final Kryo kryo = new Kryo();
		kryo.setRegistrationRequired(false);

		final Output output = new Output(1024);
		kryo.writeClassAndObject(output, new StringSupplierContainer());
		final byte[] result = output.toBytes();

		assertThat(result).isNotNull();
	}

	static class EmptyStringSupplier implements Supplier<String>, Serializable {

		@Override
		public String get() {
			return "";
		}
	}

	static class StringSupplierContainer extends SupplierContainer<String> {

		StringSupplierContainer() {
			super(new EmptyStringSupplier());
		}
	}

	static class SupplierContainer<T> {

		private final Supplier<T> input;

		SupplierContainer(Supplier<T> input) {
			this.input = input;
		}
	}
}
```

Possibly related to #648

**Comment by c14s** [comment]
With RC4, I'm also/still getting this ArrayIndexOutOfBoundsException.

Looks that in Generics.java, the method pushTypeVariables() should just return 0, if the hierarchy is empty.

With this change, the test mentioned above is passed successfully.
Or would this change just hide the root cause?

```
public int pushTypeVariables (GenericsHierarchy hierarchy, GenericType[] args) {
           
    if (hierarchy.total == 0) {
        return 0; // no type parameters, e.g. for String
    }
 [...]
```

**Comment by egorlitvinenko** [comment]
And
`
java.lang.NullPointerException: null
        at com.esotericsoftware.kryo.util.Generics.nextGenericTypes(Generics.java:93) ~[kryo-5.0.0-RC4.jar!/:na]
        at com.esotericsoftware.kryo.serializers.FieldSerializer.pushTypeVariables(FieldSerializer.java:132) ~[kryo-5.0.0-RC4.jar!/:na]
        at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:114) ~[kryo-5.0.0-RC4.jar!/:na]
        at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:696) ~[kryo-5.0.0-RC4.jar!/:na]
`

**Comment by novoj** [comment]
I've encountered the same problem and I confirm that above mentioned test reproduces the problem. I've workarounded the problem by adding this line (line:134) to `com.esotericsoftware.kryo.util.Generics#pushTypeVariables` and changing line 135:

``` java
		final int length = args.length < hierarchy.counts.length ? args.length : hierarchy.counts.length;
		for (int i = 0, p = 0, n = length; i < n; i++) {
```

It fixed my much more complex scenario and is maybe more safe than `if (hierarchy.total == 0)`. The Generics problem is regretfully too complex for me to understand the root cause, so this workaround is NOT CORRECT FIX probably.

**Comment by aijm** [comment]
I also encountered the same problem, I want to find the root cause of the problem from the source code, but I found it difficult to fully understand the code.

**Comment by MarcMil** [comment]
@NathanSweet Maybe you can shine some light on this issue? This seems like a pretty severe bug.
Judging from the responses from these different people it seems that this bug is in need of someone who deeply understands the semantics of this piece of code or we might end up with a temporary fix which only masks the problem without fixing the underlaying course.

I have encountered the same issue in kryo-serializers, which works fine with RC2, but shows this behavior starting with RC3.
As such, I thought it might be a good starting point to triage this problem by inspecting
https://github.com/EsotericSoftware/kryo/compare/kryo-parent-5.0.0-RC2...kryo-parent-5.0.0-RC3

However, I noticed that the sample in this bug report has this error even with RC1 and RC2. So this might not solve the problem either. But someone who understands this code might be able to solve this bug using the code supplied by the bug reporter.

**Comment by mbenz89** [comment]
Any intention in fixing the underlying problem? I'm also victim to this error. The proposed pr seems to lead into other issues here. Not sure it's related to this issue, eventually, I'm in need of a proper fix, though.

**Comment by haraldst** [comment]
Same here, I'm also affected by this problem. I just *have* to get my application working, so I will do some more debugging.

**Comment by haraldst** [comment]
I my case, I found the issue to be in CollectionSerializer, which misses a number of popGenericType calls in the read(...) method when length == 0.

Original:
      if (length == 0)
        return collection;

My fix:
      if (length == 0) {
        kryo.getGenerics().popGenericType();
        return collection;
      }

Same thing for
      if (length == 0)
        return null;

**Comment by borisdainson** [comment]
I have the same problem. The change suggested by @novoj  gives me StackOverflowError. This is on RC4. 

A goof fix will be much appreciated.

**Comment by OrionDevelopment** [comment]
I had this as well, however i was able to narrow it down a bit:
This happended to me because i had a field in a class with a generic wildcard: `IUIElementData<?>` which seems to be treated by some compilers as being: `IUIElementData` which has no generic element. However any implementing type will have a generic argument, even if it just `Object` which was causing the NPE.
Not sure if this helps. But I just redefined the field differently, having a proper generic argument and then it worked.

**Comment by ambition-consulting** [comment]
What a shame - 5.0 brings so much great stuff, but what is it worth when the basics are no longer working?

**Comment by OrionDevelopment** [comment]
Yeah it is a sad state of affairs to be honest. I mean this is basic stuff that worked in the older version but not in the newer. I understand that it is still in RC, at least I hope, but we are over a year further with a very real problem and with people who posted helpful information.

But i guess no answer, is also an answer...

**Comment by magro** [comment]
@NathanSweet Can you help here?

**Comment by c14s** [comment]
@NathanSweet Would be great, if you just can add a comment here.
I've updated my env to RC5, and it looks like the ArrayIndexOutOfBoundsException has been fixed.

**Comment by theigl** [comment]
I just re-ran my test against RC5 and the exception is still thrown.

**Comment by OrionDevelopment** [comment]
Yep indeed. I also ran into the same issue today again.
Again the problem at least on my end seems to be the fact that ISomeGenericClass<?> as field type seems to be treated as ISomeGenericClass without the generic parameter when Kryo is talking about the field typewise. However when it comes to actually serialize and deserialize the value that is stored inside the field it looks at it like a so: ISomeGenericClass<Object>, which obviously has a generic type causing the array out of bounds.

**Comment by magro** [comment]
A thought: you could already contribute test cases (unit tests that reproduce your issue) which could be incorporated already (being disabled so far). So if anybody would start working on this at least could tell if he solved your issue.

**Comment by theigl** [comment]
@magro: This makes sense. I'll create a PR with tests for #654 and #655 asap.

**Comment by MarcMil** [comment]
I'd argue that this kind of generic "optimization" that is currently happening should be made optional. It is rather complicated and buggy. It's only worth it when final classes are used as a generic type argument to save a little bit of space. There is actually no real need to keep track of generic types at all. Due to type erasure, the JVM is at runtime not even sure what type is used (see http://homepages.inf.ed.ac.uk/wadler/gj/Documents/gj-oopsla.pdf for details).

**Comment by theigl** [comment]
@magro: I have just pushed #717. This PR contains all currently known failing test-cases.

I will shortly create another PR that applies known fixes for these issues and resolves all these cases. All of these fixes are quite simple and as far as I can tell should not break other functionality.

**Comment by theigl** [comment]
I have pushed #718 that applies all currently known fixes and workarounds and makes all tests from #717 pass.

**Comment by magro** [comment]
Many thanks for the PR, @theigl !

Your changes are released as RC6, would be awesome to get feedback here from as many people as possible, to see if we can close this issue now.

**Comment by theigl** [comment]
My pleasure @magro!

I only compiled existing fixes and verified them with my tests. Original contributions were by @tostino, @maxisvest, and @aijm.

I'll test RC6 against my main application tomorrow.

**Comment by theigl** [comment]
Resolved in RC6.
